name: arabic_letters_app
description: "Huroofi - Arabic Letters Learning App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # Text to speech
  flutter_tts: ^4.0.2
  
  # Audio player for animal sounds
  audioplayers: ^6.1.0
  
  # Animations
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  
  # App icon generator
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/animals/
    - assets/images/objects/
    - assets/images/nature/
    - assets/sounds/letters/أ/
    - assets/sounds/letters/ب/
    - assets/sounds/letters/ت/
    - assets/sounds/letters/ث/
    - assets/sounds/letters/ج/
    - assets/sounds/letters/ح/
    - assets/sounds/letters/خ/
    - assets/sounds/letters/د/
    - assets/sounds/letters/ذ/
    - assets/sounds/letters/ر/
    - assets/sounds/letters/ز/
    - assets/sounds/letters/س/
    - assets/sounds/letters/ش/
    - assets/sounds/letters/ص/
    - assets/sounds/letters/ض/
    - assets/sounds/letters/ط/
    - assets/sounds/letters/ظ/
    - assets/sounds/letters/ع/
    - assets/sounds/letters/غ/
    - assets/sounds/letters/ف/
    - assets/sounds/letters/ق/
    - assets/sounds/letters/ك/
    - assets/sounds/letters/ل/
    - assets/sounds/letters/م/
    - assets/sounds/letters/ن/
    - assets/sounds/letters/ه/
    - assets/sounds/letters/و/
    - assets/sounds/letters/ي/
    - assets/sounds/animals/أ/
    - assets/sounds/animals/ب/
    - assets/sounds/animals/ت/
    - assets/sounds/animals/ث/
    - assets/sounds/animals/ج/
    - assets/sounds/animals/ح/
    - assets/sounds/animals/خ/
    - assets/sounds/animals/د/
    - assets/sounds/animals/ذ/
    - assets/sounds/animals/ر/
    - assets/sounds/animals/ز/
    - assets/sounds/animals/س/
    - assets/sounds/animals/ش/
    - assets/sounds/animals/ص/
    - assets/sounds/animals/ض/
    - assets/sounds/animals/ط/
    - assets/sounds/animals/ظ/
    - assets/sounds/animals/ع/
    - assets/sounds/animals/غ/
    - assets/sounds/animals/ف/
    - assets/sounds/animals/ق/
    - assets/sounds/animals/ك/
    - assets/sounds/animals/ل/
    - assets/sounds/animals/م/
    - assets/sounds/animals/ن/
    - assets/sounds/animals/ه/
    - assets/sounds/animals/و/
    - assets/sounds/animals/ي/


    - assets/sounds/nature/أ/
    - assets/sounds/nature/ب/
    - assets/sounds/nature/ت/
    - assets/sounds/nature/ث/
    - assets/sounds/nature/ج/
    - assets/sounds/nature/ح/
    - assets/sounds/nature/خ/
    - assets/sounds/nature/د/
    - assets/sounds/nature/ذ/
    - assets/sounds/nature/ر/
    - assets/sounds/nature/ز/
    - assets/sounds/nature/س/
    - assets/sounds/nature/ش/
    - assets/sounds/nature/ص/
    - assets/sounds/nature/ض/
    - assets/sounds/nature/ط/
    - assets/sounds/nature/ظ/
    - assets/sounds/nature/ع/
    - assets/sounds/nature/غ/
    - assets/sounds/nature/ف/
    - assets/sounds/nature/ق/
    - assets/sounds/nature/ك/
    - assets/sounds/nature/ل/
    - assets/sounds/nature/م/
    - assets/sounds/nature/ن/
    - assets/sounds/nature/ه/
    - assets/sounds/nature/و/
    - assets/sounds/nature/ي/

    - assets/sounds/object/أ/
    - assets/sounds/object/ب/
    - assets/sounds/object/ت/
    - assets/sounds/object/ث/
    - assets/sounds/object/ج/
    - assets/sounds/object/ح/
    - assets/sounds/object/خ/
    - assets/sounds/object/د/
    - assets/sounds/object/ذ/
    - assets/sounds/object/ر/
    - assets/sounds/object/ز/
    - assets/sounds/object/س/
    - assets/sounds/object/ش/
    - assets/sounds/object/ص/
    - assets/sounds/object/ض/
    - assets/sounds/object/ط/
    - assets/sounds/object/ظ/
    - assets/sounds/object/ع/
    - assets/sounds/object/غ/
    - assets/sounds/object/ف/
    - assets/sounds/object/ق/
    - assets/sounds/object/ك/
    - assets/sounds/object/ل/
    - assets/sounds/object/م/
    - assets/sounds/object/ن/
    - assets/sounds/object/ه/
    - assets/sounds/object/و/
    - assets/sounds/object/ي/
    
    - assets/images/animals/أ/
    - assets/images/animals/ب/
    - assets/images/animals/ت/
    - assets/images/animals/ث/
    - assets/images/animals/ج/
    - assets/images/animals/ح/
    - assets/images/animals/خ/
    - assets/images/animals/د/
    - assets/images/animals/ذ/
    - assets/images/animals/ر/
    - assets/images/animals/ز/
    - assets/images/animals/س/
    - assets/images/animals/ش/
    - assets/images/animals/ص/
    - assets/images/animals/ض/
    - assets/images/animals/ط/
    - assets/images/animals/ظ/
    - assets/images/animals/ع/
    - assets/images/animals/غ/
    - assets/images/animals/ف/
    - assets/images/animals/ق/
    - assets/images/animals/ك/
    - assets/images/animals/ل/
    - assets/images/animals/م/
    - assets/images/animals/ن/
    - assets/images/animals/ه/
    - assets/images/animals/و/
    - assets/images/animals/ي/
    
    - assets/images/nature/أ/
    - assets/images/nature/ب/
    - assets/images/nature/ت/
    - assets/images/nature/ث/
    - assets/images/nature/ج/
    - assets/images/nature/ح/
    - assets/images/nature/خ/
    - assets/images/nature/د/
    - assets/images/nature/ذ/
    - assets/images/nature/ر/
    - assets/images/nature/ز/
    - assets/images/nature/س/
    - assets/images/nature/ش/
    - assets/images/nature/ص/
    - assets/images/nature/ض/
    - assets/images/nature/ط/
    - assets/images/nature/ظ/
    - assets/images/nature/ع/
    - assets/images/nature/غ/
    - assets/images/nature/ف/
    - assets/images/nature/ق/
    - assets/images/nature/ك/
    - assets/images/nature/ل/
    - assets/images/nature/م/
    - assets/images/nature/ن/
    - assets/images/nature/ه/
    - assets/images/nature/و/
    - assets/images/nature/ي/
    

    - assets/images/objects/أ/
    - assets/images/objects/ب/
    - assets/images/objects/ت/
    - assets/images/objects/ث/
    - assets/images/objects/ج/
    - assets/images/objects/ح/
    - assets/images/objects/خ/
    - assets/images/objects/د/
    - assets/images/objects/ذ/
    - assets/images/objects/ر/
    - assets/images/objects/ز/
    - assets/images/objects/س/
    - assets/images/objects/ش/
    - assets/images/objects/ص/
    - assets/images/objects/ض/
    - assets/images/objects/ط/
    - assets/images/objects/ظ/
    - assets/images/objects/ع/
    - assets/images/objects/غ/
    - assets/images/objects/ف/
    - assets/images/objects/ق/
    - assets/images/objects/ك/
    - assets/images/objects/ل/
    - assets/images/objects/م/
    - assets/images/objects/ن/
    - assets/images/objects/ه/
    - assets/images/objects/و/
    - assets/images/objects/ي/
   


  fonts:
    - family: ArialKids
      fonts:
        - asset: assets/fonts/arial.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: "assets/icon/app_icon.png"  # Update this path to your icon image
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"  # Update this path to your icon image
